### CREAR un alimento ( pizza , empanadas o postres )
POST http://localhost:3001/api/foods
Content-Type: application/json

{
"name": "Combo fugazzeta",
"price": 2250,
"description": "2 muzzarellas, 6 empanadas, 2 Coca cola de 1,5Lts",
"measurement": "1",
"category": "promociones",
"show": 1,
"available": 1
}

### EDITAMOS un alimento
PUT http://localhost:3001/api/foods/6219c08c276414f882fe9ec4
Content-Type: application/json

{
  "name": "torta",
  "price": 120,
  "description": "Chocolate",
  "measurement": "1/2",
  "category": "postres",
  
}

### OBTENER todos los alimentos
GET http://localhost:9000/api/foods
Content-Type: application/json

### ELIMINAR un alimento
DELETE http://localhost:3001/api/foods/621eb4487f929681700cebc2
Content-Type: application/json

### OBTENER detalle de un producto
GET http://localhost:3001/api/foods/6219b167d45221fc82915d8a
Content-Type: application/json


### OBTENER alimentos por categoria
GET http://localhost:3001/api/foods/category/empanadas
Content-Type: application/json


