### Eliminamos un elemento del carrito
DELETE http://localhost:3001/api/cart
Content-Type: application/json; charset=utf-8

{
    "userId":"6219c08c276414f882fe9ec4",
    "productId":"62155ce4d73535f90bf388f2"
}

### Obtener el Carrito de compra de un cliente
GET http://localhost:3001/api/cart/61fefe099cd102d5143243eb
Content-Type: application/json; charset=utf-8

### Agregar al carrito un producto
POST http://localhost:3001/api/cart/
Content-Type: application/json; charset=utf-8

{
    "productId": "6219c08c276414f882fe9ec4",
    "userId": "61fefe099cd102d5143243eb"
}


### Eliminar todo el carrito
DELETE http://localhost:3001/api/cart/61fefe099cd102d5143243eb
Content-Type: application/json; charset=utf-8


### Aumentar la cantidad de un producto
POST http://localhost:3001/api/cart/more
Content-Type: application/json; charset=utf-8

{
"productId":"621bbfc40cfd1f55c9a8ff5f",
"userId":"61fefe099cd102d5143243eb"
}

### Disminuir la cantidad de un producto
POST http://localhost:3001/api/cart/less
Content-Type: application/json; charset=utf-8

{
"productId":"621bbfc40cfd1f55c9a8ff5f",
"userId":"61fefe099cd102d5143243eb"
}

### Realizar la orden del pedido
GET http://localhost:3001/api/cart/order/61fefe099cd102d5143243eb
Content-Type: application/json; charset=utf-8


