### Eliminamos un elemento del carrito
DELETE http://localhost:3001/api/cart
Content-Type: application/json; charset=utf-8

{
    "productId":"6219c113276414f882fe9eca",
    "userId":"61fefe099cd102d5143243eb"
}

### Obtener el Carrito de compra de un cliente
GET http://localhost:3001/api/cart/61fefe099cd102d5143243eb
Content-Type: application/json; charset=utf-8

### Agregar al carrito un producto
POST http://localhost:3001/api/cart/
Content-Type: application/json; charset=utf-8

{
    "productId": "6219c113276414f882fe9eca",
    "userId": "61fefe099cd102d5143243eb"
}


### Eliminar todo el carrito
DELETE http://localhost:3001/api/cart/61fefe099cd102d5143243eb
Content-Type: application/json; charset=utf-8


### Aumentar la cantidad de un producto
POST http://localhost:3001/api/cart/more
Content-Type: application/json; charset=utf-8

{
"productId":"621d78c1d6eeb2d46f0995ae",
"userId":"61fefe099cd102d5143243eb"
}

### Disminuir la cantidad de un producto
POST http://localhost:3001/api/cart/less
Content-Type: application/json; charset=utf-8

{
"productId":"621d78c1d6eeb2d46f0995ae",
"userId":"61fefe099cd102d5143243eb"
}

### Realizar la orden del pedido
GET http://localhost:3001/api/cart/order/61fefe099cd102d5143243eb
Content-Type: application/json; charset=utf-8


