### CREAR un alimento ( pizza , empanadas o postres )
POST http://localhost:3001/api/foods
Content-Type: application/json

{
  "name": "Carne suave",
  "price": 120,
  "description": "de carne sin condimentos fuertes",
  "measurement": "1",
  "category": "empanadas"
}

### EDITAMOS un alimento
PUT http://localhost:3001/api/foods/6219c08c276414f882fe9ec4
Content-Type: application/json

{
  "name": "torta",
  "price": 120,
  "description": "Chocolate",
  "measurement": "1/2",
  "category": "postres"
}

### OBTENER todos los alimentos
GET http://localhost:3001/api/foods
Content-Type: application/json

### ELIMINAR un alimento
DELETE http://localhost:3001/api/foods/6219b008d1f4f856a0256795
Content-Type: application/json

### OBTENER detalle de un producto
GET http://localhost:3001/api/foods/6219b167d45221fc82915d8a
Content-Type: application/json


### OBTENER alimentos por categoria
GET http://localhost:3001/api/foods/category/empanadas
Content-Type: application/json


