### Obtener todas las bebidas
GET http://localhost:9000/api/drinks/
Content-Type: application/json; charset=utf-8

### Crear una bebida
POST http://localhost:9000/api/drinks/
Content-Type: application/json; charset=utf-8

{
"brand":"coca cola",
"title":"coca cola zero",
"measurement":"l",
"size":1.5,
"price":200,
"category": "empanadas"
}

### Editar una bebida
PATCH http://localhost:9000/api/drinks/621d78c1d6eeb2d46f0995ae
Content-Type: application/json; charset=utf-8

{
"category": "bebidas"
}

### OBTENER detalle de bebida
GET http://localhost:9000/api/drinks/621d78c1d6eeb2d46f0995ae
Content-Type: application/json

### OBTENER todas las bebidas
GET http://localhost:9000/api/drinks
Content-Type: application/json

### ELIMINAR una bebida
DELETE http://localhost:9000/api/drinks/62155ce4d73535f90bf388f2
Content-Type: application/json



### OBTENER bebida por subcategoria
GET http://localhost:9000/api/drinks/category/empanadas
Content-Type: application/json


### ELIMINAR TODA LAS BEBIDAS
DELETE http://localhost:9000/api/drinks/
Content-Type: application/json

